<?php
/**
 * bosa_extras module
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 * @version $0.1
 * @copyright 2012 bellcom open source aps
 **/

function bosa_extras_init() {

  if(arg(0) == 'checkout')
  {
    global $language;
    $node = node_load(15);
    $terms = array('terms' => $node->body[$language->language][0]['safe_value']);

    drupal_add_js(array('bosa_extras' => $terms), 'setting');
    drupal_add_js(drupal_get_path('module', 'bosa_extras').'/js/jquery.Terms.js');
  }

  drupal_add_library('system','ui.datepicker');
  drupal_add_js(drupal_get_path('module', 'bosa_extras').'/js/jquery.toggleText.js');
  drupal_add_js(drupal_get_path('module', 'bosa_extras').'/js/jquery.salesDatepicker.js');
  drupal_add_js(drupal_get_path('module', 'bosa_extras').'/js/jquery.inCart.js');
}

function bosa_extras_user_login(&$edit, $account) {
if (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset' || variable_get('login_destination_immediate_redirect', FALSE)) {
  drupal_goto('offer-publisher/');
}
}
